# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

# conda, mac, simg
variables:
    NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
    NF_PROCESS_FILES: "modules/local/wf-human-snp.nf modules/local/wf-human-sv.nf"
    NF_IGNORE_PROCESSES: "hap,lookup_clair3_model,phase_contig_haplotag,merge_haplotagged_contigs,makeAlignmentReport.\
                        get_genome,aggregate_all_variants,aggregate_full_align_variants,aggregate_pileup_variants,create_candidates,\
                        evaluate_candidates,get_qual_filter,makeReport,make_chunks,merge_pileup_and_full_vars,output_snp,phase_contig,\
                        pileup_variants,post_clair_phase_contig,select_het_snps,vcfStats"
    NF_WORKFLOW_OPTS: "--snp --sv --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phased --annotation_threads 4"
    CI_FLAVOUR: "new"
    PYTEST_CONTAINER_CONFIG_KEY: "e2l_base_tag"

check-models:
    extends: .preflight
    script:
        - !reference [.install, nextflow] # requires nextflow to read config
        - bash util/update_models_schema.sh . docker
        - >
            if ! diff nextflow_schema.json nextflow_schema.json.new; then
                echo "Model schema requires updating."
                exit 1
            fi

docker-run:
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude:
            - ${CI_PROJECT_NAME}/**/*.bam
            - ${CI_PROJECT_NAME}/**/*.cram
            - ${CI_PROJECT_NAME}/**/*.fa
            - ${CI_PROJECT_NAME}/**/*.fna
            - ${CI_PROJECT_NAME}/**/*.fasta
            - ${CI_PROJECT_NAME}/**/ref_cache/**

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "gzref-bam-mod",
                "gzref-bam-mod-hap",
                "wf-human-snp_modelint",
                "wf-human-snp_modelint_unphase",
                "wf-human-snp_modelext",
                "wf-human-snp_covblock",
                "wf-human-snp_svrefine",
                "wf-human-sv",
                "wf-human-sv-phase",
                "wf-human-str",
                "wf-human-cnv-ubam-to-bam",
                "wf-human-cnv-cram-to-bam",
                "wf-human-phase_all",
                "wf-human-phase_all_sep",
                "wf-human-phase_all_sep_wh",
                "gzref-ucram-mod",
                "downsample"
              ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never

        - if: $MATRIX_NAME == "wf-human-snp_modelint"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,phase_contig_haplotag,merge_haplotagged_contigs,phase_contig,getGenome,get_coverage,getVersions,getParams,failedQCReport,refine_with_sv,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp --sv false --mod false --cnv false --str false --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --basecaller_cfg clair3:dna_r10.4.1_e8.2_400bps_hac_prom --phased --bam_min_coverage 0.00001 --annotation_threads 4"

        - if: $MATRIX_NAME == "wf-human-snp_modelint_unphase"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,phase_contig_haplotag,post_clair_phase_contig,merge_haplotagged_contigs,phase_contig,getGenome,get_coverage,getVersions,getParams,failedQCReport,refine_with_sv,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp --sv false --mod false --cnv false --str false --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --basecaller_cfg clair3:dna_r10.4.1_e8.2_400bps_hac_prom --bam_min_coverage 0.00001 --annotation_threads 4"

        - if: $MATRIX_NAME == "wf-human-snp_modelext"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,lookup_clair3_model,phase_contig,phase_contig_haplotag,merge_haplotagged_contigs,getGenome,get_coverage,getVersions,getParams,failedQCReport,refine_with_sv,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp --sv false --mod false --cnv false --str false --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phased --bam_min_coverage 0.00001 --annotation_threads 4"

        - if: $MATRIX_NAME == "wf-human-snp_covblock"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,lookup_clair3_model,phase_contig_haplotag,merge_haplotagged_contigs,\
                                    getGenome,aggregate_all_variants,aggregate_full_align_variants,aggregate_pileup_variants,create_candidates,\
                                    evaluate_candidates,get_qual_filter,makeReport,make_chunks,merge_pileup_and_full_vars,output_snp,phase_contig,\
                                    pileup_variants,post_clair_phase_contig,select_het_snps,vcfStats,refine_with_sv,annotate_vcf,bed_filter"
              NF_WORKFLOW_OPTS: "--snp --sv false --mod false --cnv false --str false --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phased --bam_min_coverage 100"

        - if: $MATRIX_NAME == "wf-human-snp_svrefine"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,lookup_clair3_model,phase_contig_haplotag,merge_haplotagged_contigs,makeAlignmentReport.\
                                    get_genome,aggregate_all_variants,aggregate_full_align_variants,aggregate_pileup_variants,create_candidates,\
                                    evaluate_candidates,get_qual_filter,makeReport,make_chunks,merge_pileup_and_full_vars,output_snp,phase_contig,\
                                    pileup_variants,post_clair_phase_contig,select_het_snps,vcfStats"
              NF_WORKFLOW_OPTS: "--snp --sv --mod false --cnv false --str false --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phased --annotation_threads 4"

        - if: $MATRIX_NAME == "wf-human-sv"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-sv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf"
              NF_IGNORE_PROCESSES: "getAllChromosomesBed,minimap2_alignment,get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,annotate_vcf"
              NF_WORKFLOW_OPTS: "--snp false --sv --mod false --cnv false --str false --bam demo_data/test.bam --ref demo_data/chr20_human_g1k_v37_part.fasta.gz --bed demo_data/target.bed --tr_bed demo_data/human_hs37d5.trf.bed --bam_min_coverage 0.00001 --annotation_threads 4"

        - if: $MATRIX_NAME == "wf-human-sv-phase"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf"
              NF_IGNORE_PROCESSES: "getAllChromosomesBed,minimap2_alignment,get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,annotate_vcf"
              NF_WORKFLOW_OPTS: "--mod false --cnv false --str false --sv true --snp true --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --annotation_threads 4 --phased"

        - if: $MATRIX_NAME == "wf-human-cnv"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-cnv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-cnv.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod false --cnv --str false --bam demo_data/test.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz --bin_size 500 --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "gzref-ucram-mod"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-methyl/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf"
              NF_IGNORE_PROCESSES: "index_ref_gzi,mapula,getGenome,get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,annotate_vcf,eval_downsampling,downsampling,compress_bed,modkit,modkit_phase"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod --cnv false --str false --bam demo_data/demo.ucram --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 --ubam_bam2fq_threads 1 --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "gzref-bam-mod-hap"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-methyl/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf"
              NF_IGNORE_PROCESSES: "minimap2_ubam,index_ref_gzi,mapula,get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,annotate_vcf,eval_downsampling,downsampling,modkit"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod --cnv false --str false --bam demo_data/demo.cram --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 --ubam_bam2fq_threads 1 --bam_min_coverage 0.00001 --phased --annotation false"

        - if: $MATRIX_NAME == "gzref-bam-mod"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-methyl/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf"
              NF_IGNORE_PROCESSES: "minimap2_ubam,index_ref_gzi,mapula,get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,annotate_vcf,eval_downsampling,downsampling,modkit_phase"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod --cnv false --str false --bam demo_data/demo.cram --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 --ubam_bam2fq_threads 1 --bam_min_coverage 0.00001 --annotation false"

        - if: $MATRIX_NAME == "downsample"
          variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-str/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf"
              NF_IGNORE_PROCESSES: "minimap2_ubam,index_ref_gzi,mapula,getGenome,get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,eval_downsampling,downsampling,compress_bed,modkit_phase,annotate_vcf"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod --annotation false --bam demo_data/demo.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz \
              --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 \
              --ubam_bam2fq_threads 1 --bam_min_coverage 0 --skip_annotation \
              --downsample_coverage --downsample_coverage_target 10"

        - if: $MATRIX_NAME == "wf-human-str"
          variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-str/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-str.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod false --cnv false --str --bam demo_data/demo.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name demo --sex female --bam_min_coverage 0.00001 --annotation false"

        - if: $MATRIX_NAME == "wf-human-phase_all"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf modules/local/wf-human-snp.nf workflows/phasing.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,hap,phase_contig,post_clair_phase_contig,bed_filter"
              NF_WORKFLOW_OPTS: "--mod false --cnv false --str false --sv --snp --phased --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --sample_name demo --sex female --bam_min_coverage 0.00001 --annotation false"

        - if: $MATRIX_NAME == "wf-human-phase_all_sep"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf modules/local/wf-human-snp.nf workflows/phasing.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,hap,phase_contig,post_clair_phase_contig,bed_filter"
              NF_WORKFLOW_OPTS: "--mod false --cnv false --str false --sv --snp --phased --output_separate_phased --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --sample_name demo --sex female --bam_min_coverage 0.00001 --annotation false"

        - if: $MATRIX_NAME == "wf-human-phase_all_sep_wh"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf modules/local/wf-human-snp.nf workflows/phasing.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport,hap,phase_contig,post_clair_phase_contig,bed_filter"
              NF_WORKFLOW_OPTS: "--mod false --cnv false --str false --sv --snp --phased --output_separate_phased --use_longphase false --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --sample_name demo --sex female --bam_min_coverage 0.00001 --annotation false"


aws-run:
    stage: test
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude:
            - ${CI_PROJECT_NAME}/**/*.bam
            - ${CI_PROJECT_NAME}/**/*.cram
            - ${CI_PROJECT_NAME}/**/*.fa
            - ${CI_PROJECT_NAME}/**/*.fna
            - ${CI_PROJECT_NAME}/**/*.fasta
            - ${CI_PROJECT_NAME}/**/ref_cache/**
    variables:
        CWG_AWS_ENV_NAME: "stack"

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "wf-human-cnv-ubam-to-bam",
                "wf-human-cnv-cram-to-bam",
              ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never

        - if: $MATRIX_NAME == "wf-human-cnv-cram-to-bam"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-cnv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-cnv.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod false --cnv --str false --bam demo_data/test.cram --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz --bin_size 500 --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "wf-human-cnv-ubam-to-bam"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-cnv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-cnv.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport,makeAlignmentReport"
              NF_WORKFLOW_OPTS: "--snp false --sv false --mod false --cnv --str false --bam demo_data/test.ubam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz --bin_size 500 --bam_min_coverage 0.00001"

macos-run:
  # Let's avoid those ARM64 runners for now
  tags:
    - macos
    - x86
